rm thesis.aux
rm thesis.bbl
rm thesis.blg
rm thesis.loa
rm thesis.lof
rm thesis.log
rm thesis.lol
rm thesis.lot
rm thesis.out
rm thesis.pdf
rm thesis.run.xml
rm thesis.synctex.gz
rm thesis.toc
rm thesis-blx.bib
